const MAX_FOOBARS = 20;

const IDLE = 'IDLE';
const MINING_FOO = 'MINING_FOO';
const MINING_BAR = 'MINING_BAR';
const BUILDING_FOOBAR = 'BUILDING_FOOBAR';
const TRANSFERRING = 'TRANSFERRING';

const MINE_FOO = 'MINE_FOO';
const MINE_BAR = 'MINE_BAR';
const BUILD_FOOBAR = 'BUILD_FOOBAR';

export {
  MAX_FOOBARS,
  IDLE,
  MINING_FOO,
  MINING_BAR,
  BUILDING_FOOBAR,
  TRANSFERRING,
  MINE_FOO,
  MINE_BAR,
  BUILD_FOOBAR,
};